### ISSUE TITLE
Build and ship update with Travis to S3

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/csh-material-login#24]
Every commit to master should build a zip file that gets uploaded to s3 for the keycloak docker instance to pull

**Comment by mfrancis95** [comment]
A `.travis.yml` like this might work.

```yml
before_deploy: mkdir upload && zip latest.zip yourfileshere && mv latest.zip upload
deploy:
    access_key_id: $ACCESS_KEY
    bucket: $BUCKET
    edge: true
    endpoint: $ENDPOINT
    force_path_style: true
    local_dir: upload
    provider: s3
    secret_access_key: $SECRET_KEY
language: minimal
```
If Travis is complaining that the `zip` command doesn't exist, then you need to insert this into the .yml:
```yml
install: sudo apt-get install zip
```
